// ============ ARMORY DATA ============
export const DEFAULT_ARMORY = [
  {
    id: 'breathing',
    name: 'Paced Breathing',
    icon: '🌬️',
    description: 'Breathe in 4s → Hold 2s → Breathe out 6s → Hold 2s',
    technique: '4-2-6-2 paced breathing',
    unlockCondition: null,
    unlocked: true,
    practiceCount: 0,
  },
  {
    id: 'grounding',
    name: '5-4-3-2-1 Grounding',
    icon: '⚓',
    description: 'Name 5 things you see, 4 you feel, 3 you hear, 2 you smell, 1 you taste',
    technique: '5-4-3-2-1 senses grounding',
    unlockCondition: { requiresToolId: 'breathing', practiceCount: 2 },
    unlocked: false,
    practiceCount: 0,
  },
  {
    id: 'allowing',
    name: 'Allow the Storm',
    icon: '🛡️',
    description: 'Make space for anxiety without fighting it — let it pass like a wave',
    technique: 'Acceptance & defusion',
    unlockCondition: { requiresToolId: 'grounding', practiceCount: 2 },
    unlocked: false,
    practiceCount: 0,
  },
  {
    id: 'values',
    name: 'Value Anchoring',
    icon: '💎',
    description: 'Recall your deepest value to steady yourself in the moment',
    technique: 'Values-based grounding',
    unlockCondition: { requiresToolId: 'allowing', practiceCount: 2 },
    unlocked: false,
    practiceCount: 0,
  },
];
