import { useState, useEffect, useRef } from "react";
import { C } from "../constants/gameData";

const PIXEL_FONT = "'Press Start 2P', 'Courier New', monospace";
const FONT_LINK = "https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap";

const NDA_TEXT = `DARER ORDER — CONFIDENTIALITY AGREEMENT

Last Updated: April 21, 2026
Version: 1.0

This Confidentiality Agreement ("Agreement") is entered into between the DARER Project ("we," "us," or "the App") and you, the user ("Participant"), upon your access to and use of the DARER Journey application ("the App").

BY CLICKING "I AGREE" BELOW, YOU ARE ENTERING INTO A LEGALLY BINDING AGREEMENT. PLEASE READ CAREFULLY.

1. PURPOSE

The DARER App is an interactive social anxiety coaching tool designed to help participants build confidence in social situations through graduated practice and AI-guided support. The coaching frameworks incorporate evidence-based CBT/ACT principles. During your use, you will be exposed to proprietary coaching frameworks, AI-generated content, and unique game-mechanic designs that are the intellectual property of the DARER Project.

2. CONFIDENTIAL INFORMATION

"Confidential Information" means any non-public information you encounter through the App, including but not limited to:

(a) Coaching frameworks, practice exercises, and skill-building protocols used within the App
(b) AI system prompts, conversation flows, and coaching dialogue generated by the App's AI companion ("Dara")
(c) Game mechanics, visual designs, and narrative content
(d) Any other proprietary methodologies or designs not publicly available

Confidential Information does NOT include information that is:
- Already publicly available through no fault of yours
- Independently developed by you without reference to the App
- Required to be disclosed by law (with prior notice to us)

3. YOUR OBLIGATIONS

By agreeing to this Agreement, you commit to:

(a) Not copying, reproducing, distributing, or reverse-engineering any proprietary content, coaching frameworks, or AI-generated material from the App
(b) Not sharing, publishing, or otherwise disclosing any Confidential Information to any third party
(c) Not using Confidential Information to create, develop, or train any competing product, service, or AI model
(d) Not recording, screenshotting, or archiving coaching conversations with the AI companion for any purpose other than your personal use

4. YOUR DATA AND PRIVACY

(a) Personal information you share during your coaching sessions, including your social anxiety profile and personal goals, is treated as YOUR confidential information and is protected under our Privacy Policy.
(b) We will not share your personal data with third parties except as required by law or with your explicit consent.
(c) Data stored via Supabase is encrypted in transit and at rest.

5. NOT A SUBSTITUTE FOR PROFESSIONAL CARE

The DARER App is a self-guided coaching tool and does NOT constitute professional medical, psychological, or therapeutic advice. The DARER Project makes no warranty that the App will prevent, diagnose, or treat any medical or psychological condition. This App is designed to complement — not replace — professional care. If you are experiencing a mental health crisis, please contact a licensed professional or emergency services.

6. TERM

This Agreement remains in effect for as long as you use the App and for a period of two (2) years after your last use, with respect to any Confidential Information you were exposed to during use.

7. GOVERNING LAW

This Agreement shall be governed by and construed in accordance with the laws of the jurisdiction in which the DARER Project is registered, without regard to its conflict of law provisions.

8. CONTACT

For questions about this Agreement, contact us through the App or at the email address provided in the App's settings.`;

// Simple pixel-style text component (inline to avoid dependency issues)
function PixelText({ size = 8, color = "#E0D8CC", style = {}, children, ...rest }) {
  return (
    <span
      {...rest}
      style={{
        fontFamily: PIXEL_FONT,
        fontSize: size,
        color,
        letterSpacing: "0.5px",
        ...style,
      }}
    >
      {children}
    </span>
  );
}

export default function NdaAgreementScreen({ heroName, darerId, onAgree, onDecline }) {
  const [checked, setChecked] = useState(false);
  const [name, setName] = useState("");
  const [scrolling, setScrolling] = useState(false);
  const [agreed, setAgreed] = useState(false);
  const [saving, setSaving] = useState(false);
  const scrollRef = useRef(null);

  // Check if user has scrolled to the bottom (within 40px)
  const handleScroll = () => {
    const el = scrollRef.current;
    if (!el) return;
    const atBottom = el.scrollHeight - el.scrollTop - el.clientHeight < 40;
    if (atBottom && !scrolling) setScrolling(true);
  };

  const canAgree = checked && name.trim().length > 0 && scrolling && !agreed;

  const handleAgree = async () => {
    if (!canAgree) return;
    setSaving(true);
    const success = await onAgree(name.trim(), NDA_TEXT);
    if (success) {
      setAgreed(true);
    }
    setSaving(false);
  };

  const handleDecline = () => {
    if (onDecline) onDecline();
  };

  // === AGREED SCREEN ===
  if (agreed) {
    return (
      <div style={{
        minHeight: "100vh", background: C.mapBg,
        display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
        padding: "32px 24px",
      }}>
        <link href={FONT_LINK} rel="stylesheet" />
        <div style={{ fontSize: 48, marginBottom: 16 }}>📜</div>
        <PixelText size={14} color={C.hpGreen} style={{ display: "block", marginBottom: 8, textAlign: "center" }}>
          AGREEMENT SIGNED
        </PixelText>
        <PixelText size={8} color={C.grayLt} style={{ display: "block", marginBottom: 24, textAlign: "center", lineHeight: 1.8 }}>
          Welcome to the DARER Order, {heroName}.<br />Your journey begins now.
        </PixelText>
        <button
          onClick={() => window.location.reload()}
          style={{
            fontFamily: PIXEL_FONT, fontSize: 10, padding: "12px 32px",
            background: C.gold, color: C.charcoal, border: "2px solid " + C.goldMd,
            borderRadius: 4, cursor: "pointer",
          }}
        >
          BEGIN YOUR JOURNEY →
        </button>
      </div>
    );
  }

  // === MAIN NDA SCREEN ===
  return (
    <div style={{
      minHeight: "100vh", background: C.mapBg,
      display: "flex", flexDirection: "column", alignItems: "center",
      padding: "24px 20px",
    }}>
      <link href={FONT_LINK} rel="stylesheet" />

      {/* Header */}
      <div style={{ textAlign: "center", marginBottom: 16 }}>
        <div style={{ fontSize: 36, marginBottom: 8 }}>📜</div>
        <PixelText size={12} color={C.goldMd} style={{ display: "block", marginBottom: 4 }}>
          CONFIDENTIALITY AGREEMENT
        </PixelText>
        <PixelText size={7} color={C.grayLt} style={{ display: "block" }}>
          Please read and sign before entering the DARER Order
        </PixelText>
      </div>

      {/* Scrollable agreement text */}
      <div
        ref={scrollRef}
        onScroll={handleScroll}
        style={{
          width: "100%", maxWidth: 400,
          maxHeight: "45vh", overflowY: "auto",
          padding: "16px", marginBottom: 16,
          background: "#1A1218", border: "2px solid #5C3A50",
          borderRadius: 6,
        }}
      >
        <PixelText size={7} color={C.cream} style={{ display: "block", whiteSpace: "pre-wrap", lineHeight: 1.8 }}>
          {NDA_TEXT}
        </PixelText>
      </div>

      {/* Scroll indicator */}
      {!scrolling && (
        <div style={{ textAlign: "center", marginBottom: 12, animation: "fadeIn 1s ease-in-out infinite" }}>
          <PixelText size={6} color={C.amber}>↓ Scroll to read the full agreement ↓</PixelText>
        </div>
      )}

      {/* Agreement form */}
      <div style={{
        width: "100%", maxWidth: 400,
        padding: "16px",
        background: "#1A1218", border: "2px solid #5C3A50",
        borderRadius: 6,
      }}>
        {/* Checkbox */}
        <label style={{
          display: "flex", alignItems: "flex-start", gap: 10, marginBottom: 14,
          cursor: "pointer",
        }}>
          <input
            type="checkbox"
            checked={checked}
            onChange={() => setChecked(!checked)}
            style={{
              marginTop: 4, width: 16, height: 16, cursor: "pointer",
              accentColor: C.gold,
            }}
          />
          <PixelText size={7} color={C.cream} style={{ lineHeight: 1.6 }}>
            I have read and agree to the terms of the Confidentiality Agreement above.
          </PixelText>
        </label>

        {/* Signature field */}
        <div style={{ marginBottom: 16 }}>
          <PixelText size={7} color={C.goldMd} style={{ display: "block", marginBottom: 6 }}>
            Type your full name as your digital signature:
          </PixelText>
          <input
            value={name}
            onChange={e => setName(e.target.value)}
            placeholder="Your full name..."
            style={{
              width: "100%", padding: "10px 12px",
              background: C.mapBg, border: `2px solid ${checked ? C.goldMd : "#5C3A50"}`,
              borderRadius: 3, color: C.cream, fontSize: 13,
              fontFamily: PIXEL_FONT, outline: "none",
              transition: "border-color 0.3s",
            }}
          />
        </div>

        {/* Buttons */}
        <div style={{ display: "flex", gap: 12 }}>
          <button
            onClick={handleDecline}
            disabled={saving}
            style={{
              flex: 1, padding: "12px",
              background: "#5C3A50", color: C.grayLt,
              border: "2px solid #5C3A50", borderRadius: 4,
              fontFamily: PIXEL_FONT, fontSize: 9, cursor: "pointer",
              opacity: saving ? 0.5 : 1,
            }}
          >
            I DO NOT AGREE
          </button>
          <button
            onClick={handleAgree}
            disabled={!canAgree || saving}
            style={{
              flex: 1, padding: "12px",
              background: canAgree && !saving ? C.gold : "#3A2830",
              color: canAgree && !saving ? C.charcoal : C.grayLt,
              border: `2px solid ${canAgree && !saving ? C.goldMd : "#5C3A50"}`,
              borderRadius: 4,
              fontFamily: PIXEL_FONT, fontSize: 9,
              cursor: canAgree && !saving ? "pointer" : "not-allowed",
              boxShadow: canAgree && !saving ? `0 0 12px ${C.goldMd}30` : "none",
            }}
          >
            {saving ? "SAVING..." : "I AGREE →"}
          </button>
        </div>
      </div>


    </div>
  );
}
